development:
  adapter: postgresql
  encoding: unicode
  database: mysterious_dev
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mysterious_test
  pool: 5
  username: postgres
  password:
